// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSKfTWUmLJ6JEN3iNXhO0B7OLEv6p2wDk',
    appId: '1:411958732249:web:597d5f1e4821b8cb37a5c8',
    messagingSenderId: '411958732249',
    projectId: 'dinenow-973ac',
    authDomain: 'dinenow-973ac.firebaseapp.com',
    storageBucket: 'dinenow-973ac.appspot.com',
    measurementId: 'G-49N1WZ27ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTtWl_fvdDpcyPC0IpWUO4WTGsWvUbGh8',
    appId: '1:411958732249:android:cc0227d71c9abf9237a5c8',
    messagingSenderId: '411958732249',
    projectId: 'dinenow-973ac',
    storageBucket: 'dinenow-973ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8qYql1ZmWAfXdjPVA6M9wkX9_sFnWGR4',
    appId: '1:411958732249:ios:164e8696afa603a837a5c8',
    messagingSenderId: '411958732249',
    projectId: 'dinenow-973ac',
    storageBucket: 'dinenow-973ac.appspot.com',
    iosBundleId: 'com.dn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8qYql1ZmWAfXdjPVA6M9wkX9_sFnWGR4',
    appId: '1:411958732249:ios:164e8696afa603a837a5c8',
    messagingSenderId: '411958732249',
    projectId: 'dinenow-973ac',
    storageBucket: 'dinenow-973ac.appspot.com',
    iosBundleId: 'com.dn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSKfTWUmLJ6JEN3iNXhO0B7OLEv6p2wDk',
    appId: '1:411958732249:web:517a094ca78ac7ca37a5c8',
    messagingSenderId: '411958732249',
    projectId: 'dinenow-973ac',
    authDomain: 'dinenow-973ac.firebaseapp.com',
    storageBucket: 'dinenow-973ac.appspot.com',
    measurementId: 'G-X4YZ9VW742',
  );
}
